source "https://rubygems.org"

gem "nokogiri", "< 1.10.9"
gem "kramdown", ">= 2.3.0"

gem "jekyll", "~> 4.0.1"
gem "minima"
gem "public_suffix"

group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.12"
  gem 'jekyll-octicons'
  gem 'jekyll-remote-theme'
  gem "jekyll-twitter-plugin"
  gem 'jekyll-relative-links'
  gem 'jekyll-seo-tag'
  gem 'jekyll-toc'
  gem 'jekyll-gist'
  gem 'jekyll-paginate'
  gem 'jekyll-sitemap'
end

gem "kramdown-math-katex"
gem "jemoji"
gem "faraday", "< 1.0"

